### ISSUE TITLE
Quarto Source Code for Book

### ISSUE THREAD

**Issue by AhmedThahir** [robjhyndman/fpp3_slides#2]
Hi Prof. Hyndman

I was unable to find qmd files for https://otexts.com/fpp3 e-book, similar to your GitHub repo https://github.com/robjhyndman/weird.

Just want to inquire if it is publicly-available or is it closed-source?

**Comment by robjhyndman** [comment]
I have not made the fpp3 book source files publicly available.

**Comment by AhmedThahir** [comment]
Noted. Thank you for the response.
